version: "3"

services:
  caddy:
    container_name: caddy
    image: slothcroissant/caddy-cloudflaredns:v2.7.3
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - 443:443
      - 80:80
    environment:
      - BASE_DOMAIN=pluto.haenoe.party
    env_file:
      - caddy.env

volumes:
  caddy_data:
  caddy_config:


networks:
  default:
    external: true
    name: homelab
