version: "3"

services:
        caddy:
                image: haenoe/caddy-cloudflare:2
                restart: always
                volumes:
                        - ./Caddyfile:/etc/caddy/Caddyfile
                        - caddy_data:/data
                        - caddy_config:/config
                ports:
                        - 443:443
                        - 80:80
                env_file:
                        - caddy.env

volumes:
        caddy_data:
        caddy_config:
