version: "3"

secrets:
        FOO_BAR:
                file: ./my-secret.txt

services:
        caddy:
                container_name: caddy
                image: haenoe/caddy-cloudflare:2
                restart: always
                volumes:
                        - ./Caddyfile:/etc/caddy/Caddyfile
                        - caddy_data:/data
                        - caddy_config:/config
                ports:
                        - 443:443
                        - 80:80
                env_file:
                        - caddy.env

volumes:
        caddy_data:
        caddy_config:
networks:
        default:
                external: true
                name: homelab
