version: "3"

services:
        vaultwarden:
                image: vaultwarden/server:latest
                restart: always
                volumes:
                        - vaultwarden-data:/data/
                ports:
                        - "8080:80"
                environment:
                        WEBSOCKET_ENABLED: "true"
                        SIGNUPS_ALLOWED: "true"
                        SENDS_ALLOWED: "false"
                env_file:
                        - vaultwarden.env
        backup:
                image: ttionya/vaultwarden-backup:latest
                restart: always
                environment:
                        CRON: "0 * * * *"
                        ZIP_TYPE: "7z"
                        BACKUP_FILE_SUFFIX: "%Y%m%d%H%M"
                        TIMEZONE: "Europe/Berlin"
                volumes:
                        - vaultwarden-data:/bitwarden/data/
                        - vaultwarden-rclone-data:/config/
                env_file:
                        - vaultwarden.env

volumes:
        vaultwarden-data:
                name: vaultwarden-data
        vaultwarden-rclone-data:
                external: true
                name: vaultwarden-rclone-data

