version: "3"

secrets:
  ZIP_PASSWORD:
    file: ZIP_PASSWORD.secret

services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    restart: always
    volumes:
      - vaultwarden-data:/data/
    environment:
      WEBSOCKET_ENABLED: "true"
      SIGNUPS_ALLOWED: "true"
      SENDS_ALLOWED: "false"
      DOMAIN: https://vaultwarden.haenoe.xyz

  backup:
    container_name: vaultwarden-backup
    image: ttionya/vaultwarden-backup:1.16.0
    restart: always
    environment:
      CRON: "0 * * * *"
      ZIP_TYPE: "7z"
      BACKUP_FILE_SUFFIX: "%Y%m%d%H%M"
      TIMEZONE: "Europe/Berlin"
      ZIP_PASSWORD_FILE: /run/secrets/ZIP_PASSWORD
      PING_URL: https://uptime.haenoe.xyz/api/push/P18phwwIMX?status=up&msg=OK&ping=
    volumes:
      - vaultwarden-data:/bitwarden/data/
      - vaultwarden-rclone-data:/config/
    secrets:
      - ZIP_PASSWORD

volumes:
  vaultwarden-data:
    name: vaultwarden-data
  vaultwarden-rclone-data:
    external: true
    name: vaultwarden-rclone-data

networks:
  default:
    external: true
    name: homelab
