title: "Dashboard"
stylesheet:
  - "assets/theme.css"
logo: "assets/dark_circle.png"

connectivityCheck: true

links:
  - name: "Startpage"
    icon: "fas fa-file-alt"
    url: "#"
  - name: "Homelab"
    icon: "fas fa-server"
    url: "#homelab"

services:
  - name: "Search"
    icon: "fa-solid fa-globe"
    items:
      - name: "Duckduckgo"
        logo: "assets/aegis-icons/Duckduckgo.svg"
        url: "https://duckduckgo.com"
      - name: "Google"
        logo: "assets/aegis-icons/Google.svg"
        url: "https://google.com"
      - name: "YouTube"
        logo: "assets/aegis-icons/Youtube.svg"
        url: "https://youtube.com"
  - name: "Programming"
    icon: "fa-solid fa-keyboard"
    items:
      - name: "Github"
        logo: "assets/aegis-icons/GitHub.svg"
        url: "https://github.com"
