title: "Dashboard"
stylesheet:
  - "assets/theme.css"
logo: "assets/dark_circle.png"

connectivityCheck: true

links:
  - name: "Startpage"
    icon: "fas fa-file-alt"
    url: "#"
  - name: "Homelab"
    icon: "fas fa-server"
    url: "#homelab"

services:
  - name: "Monitoring"
    icon: "fa-solid fa-heart-pulse"
    items:
      - name: "Uptime Kuma"
        logo: "assets/service-icons/uptime-kuma.svg"
        url: "https://uptime.haenoe.xyz"
        slug: "docker"
        type: "UptimeKuma"
