version: '3'

services:
        uptime-kuma:
                image: louislam/uptime-kuma:1
                restart: always
                volumes:
                        - uptime-kuma:/app/data
                        - /var/run/docker.sock:/var/run/docker.sock
                ports:
                        - 3001:3001

volumes:
        uptime-kuma:
