version: "3"

services:
  actual-budget:
    container_name: actual-budget
    image: actualbudget/actual-server:latest-alpine
    restart: unless-stopped
    volumes:
      - actual-budget-data:/data

volumes:
  actual-budget-data:


networks:
  default:
    external: true
    name: homelab
